- hosts: localhost
  vars_prompt:
    - name: target_user
      prompt: What is your Ubuntu username?
      private: no
  vars:
    gnome_user: "{{ target_user }}"
  roles:
    - role: andrewrothstein.starship
    - role: gantsign.antigen
      users:
        - username: "{{ target_user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: romkatv/powerlevel10k
          antigen_bundles:
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions
            - name: powerlevel10k
              url: romkatv/powerlevel10k
      tags: "antigen"
    - role: diodonfrost.p10k
      tags: "p10k"
    - role: gantsign.sdkman
      sdkman_users:
        - "{{ target_user }}"
    - role: gantsign.sdkman_init
      users:
        - username: "{{ target_user }}"
      sdkman_install:
        - candidate: java
          version: '11.0.14-tem'
      sdkman_default:
        java: '11.0.14-tem'
    - role: morgangraphics.ansible_role_nvm
      default: true
      nodejs_version: "14.18.2"
      nvm_profile: "/home/{{ target_user }}/.zshrc"
      become: true
      become_user: "{{ target_user }}"
    - role: robertdebock.npm
      become: true
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: Install all packages
      ansible.builtin.package:
        name:
          - network-manager-openvpn
          - docker.io
          - heif-gdk-pixbuf
          - curl
          - direnv
          - powertop
          - powerstat
          - s-tui
          - build-essential
          - fzf
          - rcm
          - zsh
          - vim
          - maven
          - zeal
          - tldr
          - timewarrior
          - taskwarrior
          - gopass
          - golang
          - vdirsyncer
          - khal
          - gnupg2
          - git
          - rng-tools
        state: latest
      become: true
    - name: npm yarn
      npm:
        name: yarn
        global: yes
      become: true
    - name: npm vue clie-service
      npm:
        name: '@vue/cli-service'
        global: yes
      become: true
    - name: Check if Homebrew is already installed
      stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: is_brew_installed
      become: yes
      become_user: "{{ target_user }}"
    - name: Install Homebrew
      ansible.builtin.shell: |
        yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval $(/opt/homebrew/bin/brew shellenv)
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.zshrc
      when: not is_brew_installed.stat.exists
      become: yes
      become_user: "{{ target_user }}"
    - name: brew
      community.general.homebrew:
        name:
          - terraform
          - saml2aws
          - awscli
          - k9s
          - helm
          - kubectl
          - kubectx
          - docker-compose
        path: /home/linuxbrew/.linuxbrew/bin/
      become: yes
      become_user: "{{ target_user }}"
      when: is_brew_installed
    - name: change to zsh
      ansible.builtin.user:
        name: "{{ target_user }}"
        shell: /bin/zsh
        groups: "docker"
        append: true
      become: true
